### ISSUE TITLE
La partie ne se fini jamais

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/bataille_navale#1]
Couler tous les bateaux de l’adversaire mais le jeu ne s’arrête pas.

**Comment by BurkhalterY** [comment]
J'avais changé quelque chose et ça ne marchait plus, mais le code original marche, je l'ai remis comme avant.

**Comment by RemyTombez** [comment]
Le problème semble néanmoins persister si la partie est lancé via l'option "Jouer" au lieu de "Multijoueurs"

**Comment by RemyTombez** [comment]
Corrigé avec le commit 822db42a634881074fa66e4990ffd3f0d1a34764
